### ISSUE TITLE
memory management of aggregator

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#37] opened 2014-05-16 07:07 UTC
for big data sets the aggregator is not running through. currently the program is not stopping but it kind of hangs. i guess the jvm can't allocate memory for bigger hashmaps and java tries to fill up the hashmap and resolves collisions. 

there are several fixes (if memory in the aggregator is critical decrease the number of paralel tasks) change the workflow while aggregating towards aggregating several smaller sorted files and aggregate the final version with an n way aggregation merge sort.

**Comment by lschmelzeisen** [comment] 2014-06-11 11:38
Duplicate of #31

**Closed as completed by lschmelzeisen** 2014-06-11 11:38 UTC
Labels: bug, duplicate
